### ISSUE TITLE
Implement adding a photo to canvas

### ISSUE THREAD

**Issue by 1alexandra** [1alexandra/collage#10]
Implement class photo with method get_rect(weight, height) returning part of image with given shape to render on canvas.
On '+' button click add photo to canvas.

Implement moving and scaling the showing window of the photo (left-click on the photo -> it is selected (show that it's selected), now you can move the window on the photo by keyboard arrows, and you can use the mouse wheel or keyboard to adjust the scale. Do not allow scaling when the photo resolution is not sufficient for the required image size (extension). Enter or mouse click -> save changes and deselect, Esc -> cancel changes)

**Comment by Satbek** [comment]
Also there is need some way to mark the photo within we work. I think the dotted line will suit us.

Work with photos will occur through the keyboard:
* '↑', '↓', '→', '←' to move through the photo and get another parts of photo
* '[', ']' to zoom in, zoom out given part of image

**Comment by krchmark** [comment]
@1alexandra We can also close this issue.
